### PR TITLE
Removed path to your local system directories

### PR DESCRIPTION
**Pull request by heydevanand**

### CODE REVIEW

**Comment by sainipankaj15** [comment]
@heydevanand 
Thanks for doing this, One thing I want to add. Can you again add the Youtube link and the remaining explanation that you removed from README.MD that is mandtory.
Apart from that I will check once again

**Comment by heydevanand** [comment]
The README.md is now back to the original version. Thankyou!

**Comment by sainipankaj15** [comment]
Hey @heydevanand 
This means You put your changes along with my explanation. Now you removed your changes.

Check once your and my changes both suit to current repo along with the changes you made.

**Comment by heydevanand** [comment]
Oh you mean you want the README included but also with the YouTube link for the explanation of the project, right?

**Comment by heydevanand** [comment]
Now it's done I guess.. Please review and merge

**Comment by sainipankaj15** [comment]
Thanks for your effort Anand!!
Will check on the weekend and merge it

**Comment by heydevanand** [comment]
I hope you would merge it when you have time

**Comment by sainipankaj15** [comment]
@heydevanand 
merged your code

**Pull request merged**
